spring:
  application:
    name: api-edteam-processor

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
          temperature: 0.7

    openai:
      api-key: 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
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    context-path: /api/edteam/processor

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never
info:
  app:
    name: "@project.artifactId@"
    version: "@project.version@"
  contact:
    email: "sacco.andres@gmail.com"
    slack: "adsacco"

http-connector:
  hosts:
    api-sales:
      host: admin-production-307b.up.railway.app
      endpoints:
        get-sales-info:
          url: "/v1/sales"
          readTimeout: 5000
          writeTimeout: 5000
          connectionTimeout: 5000
