spring:
  application:
    name: api-edteam-processor

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3
          temperature: 0.7

    openai:
      api-key: XXXX
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7

server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    context-path: /api/edteam/processor

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never
info:
  app:
    name: "@project.artifactId@"
    version: "@project.version@"
  contact:
    email: "sacco.andres@gmail.com"
    slack: "adsacco"

http-connector:
  hosts:
    api-users:
      host: localhost
      port: 6070
      endpoints:
        get-users-files:
          url: "/api/edteam/users"
          readTimeout: 1000
          writeTimeout: 1000
          connectionTimeout: 2000
