spring:
  application:
    name: api-edteam-processor

server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    context-path: /api/edteam/processor

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never
info:
  app:
    name: "@project.artifactId@"
    version: "@project.version@"
  contact:
    email: "sacco.andres@gmail.com"
    slack: "adsacco"

http-connector:
  hosts:
    api-sales:
      host: admin-production-307b.up.railway.app
      endpoints:
        get-sales-info:
          url: "/v1/sales"
          readTimeout: 5000
          writeTimeout: 5000
          connectionTimeout: 5000
